name: Secret Scanning with Trufflehog

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Python and Trufflehog
      - name: Setup Python and Install Trufflehog
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog

      # Step 3: Run Trufflehog
      - name: Run Trufflehog Scanner
        run: |
          trufflehog filesystem --directory ./ --json > trufflehog_output.json

      # Step 4: Analyze the Trufflehog output
      - name: Analyze Trufflehog Results
        run: |
          echo "Analyzing Trufflehog results..."
          python -c '
          import json, sys
          with open("trufflehog_output.json") as file:
              results = json.load(file)
          critical_issues = [r for r in results if "CRITICAL" in r.get("severity", "").upper()]
          high_issues = [r for r in results if "HIGH" in r.get("severity", "").upper()]
          if critical_issues or high_issues:
              print(f"Critical issues found: {len(critical_issues)}")
              print(f"High issues found: {len(high_issues)}")
              sys.exit(1)
          else:
              print("No critical or high severity issues found.")
          '

      # Step 5: Upload the Trufflehog results (Optional)
      - name: Upload Trufflehog Report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-output
          path: trufflehog_output.json

      # Optional Notification Step
      - name: Notify on Failure
        if: failure()
        run: |
          echo "Secrets detected! Build failed due to high or critical issues."
