name: Secret Scanning with Trufflehog

# Trigger on all changes in code
on:
  push:  # Trigger on any push to branches or tags
    branches:
      - '**'  # Monitor all branches
    tags:
      - '**'  # Monitor all tags
  pull_request:  # Trigger on pull requests to any branch
    branches:
      - '**'

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Python and Trufflehog
      - name: Setup Python and Install Trufflehog
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog

      # Step 3: Run Trufflehog
      - name: Run Trufflehog Scanner
        run: |
          trufflehog filesystem --directory ./ --json > trufflehog_output.json

      # Step 4: Check for Secrets and Fail Build if Found
      - name: Check Trufflehog Results
        run: |
          if [ -s trufflehog_output.json ]; then
            echo "Secrets detected! Failing the build."
            cat trufflehog_output.json  # Print the findings for debugging
            exit 1
          else
            echo "No secrets detected. Build can proceed."
          fi

      # Step 5: Upload the Trufflehog results (Optional)
      - name: Upload Trufflehog Report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-output
          path: trufflehog_output.json
